import type { Metadata } from 'next';
import { BackToHomeLink } from '@/components/ui/BackToHomeLink';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'My Story | Maurik',
  description: 'The story behind how I build systems that work for the neurodivergent brain.',
};

export default function AboutPage() {
  return (
    <div className="course-page about-page">
      <header className="course-topbar">
        <div className="course-topbar-inner">
          <BackToHomeLink className="course-brand" />
        </div>
      </header>

      <main>
        <section className="course-section">
          <div className="course-section-inner">
            <div className="about-content">
              <h1>About Me</h1>
              <p>For most of my life, I thought I was the problem. I was not.</p>
              <p>I was born in 2004 in Peja, Kosovo, but I grew up in a village called Ujmir. My dad has a PhD and my mom is a teacher. The expectation from day one was clear. Follow their path, be a great student, do everything right. And for the first five years of Primary School, that is exactly what happened. In Kosovo, grades 1 to 5 work differently from most places. You have just one teacher for every subject across all five years. My mom worked at that same school. She knew everything being taught and she was there every single day making sure I studied, making sure I had the highest grades. I had no phone. I was just a competitive kid who loved football and absolutely hated losing. Those five years I was the best student in my class and the best player on the pitch.</p>
              <p>Football was not just something I played. I loved it completely. At some point during those years I even joined an academy in my city. I went for a year. Then I left, because in Kosovo football is seen as an uncertain path, something you are unlikely to make a career from. That is the reality there. But the love never left. I still watch every Real Madrid game. I still play when I can. It has always been part of who I am.</p>
              <p>The first sign that my brain worked differently came in the fourth grade. The teacher told us to memorize a full page of poetry and recite it the next day without a single mistake. I could not do it. My brain just would not take it in. I hated doing something I had no interest in and I could not memorize it for anything. At the time I had no idea why. I just knew I felt stupid and blocked.</p>
              <p>Then sixth grade came and everything started shifting. From grade 6 onward in Kosovo the system changes completely. Now there is a different teacher for every subject instead of one. It is always a difficult switch. And somewhere around that same year my aunt gave me my first phone. A cheap Samsung. I was excited because I had seen other kids having so much fun with theirs. Looking back now, that phone was the start of my downfall. My grades in sixth grade were still okay because my mom was still watching closely. But every year after that, more time on the phone meant less time on everything else. Seventh grade I got my first 4, which here goes from 1 to 5. I was very upset. I had never gotten below a 5 before. Eighth grade I got a 3. By ninth grade I got a 1 in Physics, the lowest grade possible. And that is not just a number. My confidence was falling every single year. By eighth and ninth grade it was completely gone.</p>
              <p>The darkest period of my life started right around that time. And it began completely by accident. I was not playing well in football one day and just decided to act like Cristiano Ronaldo, the player I supported at Real Madrid. It worked. I scored, I played great. Something clicked in my head. If I could switch into someone else for football, why not for studying too. Why not be like someone smart and just carry their knowledge. That is genuinely what I thought. And so it spread. One day I was Anthony Joshua. Another day Einstein. Then Kevin Hart to try to be funny around people. Then my own dad for his intelligence, my uncle for his toughness. I was switching characters every single day for around five years. And every time something went wrong, whether someone made a joke at my expense or I froze in a conversation, I thought the problem was the character I had chosen. So I would just pick a different one the next day. When I think back to those years now, I just have sympathy for actors. What they do every day is genuinely one of the hardest things a person can put themselves through. I was doing it without even knowing it, and it drained me completely. I knew Ronaldo from the pitch. I did not know how he studied, how he spoke to his family, how he handled a bad day. So I was just permanently frozen and lost inside a character I barely understood. When I think back to the worst years of my life, that is what I see. Not university, not failing exams. Those years of switching characters every single day.</p>
              <p>At home I had nobody to talk to about any of this. I had no brother. My parents loved me and gave me everything they could, but there was zero emotional connection between us. Every single conversation was just them asking if I had studied. Nothing about how I was actually doing. I do not blame them for that. My dad grew up in a family of twelve children. Nobody had time for that kind of thing back then. They gave me everything they knew how to give. But I was completely alone with my thoughts and it made me more and more closed off every year.</p>
              <p>When I moved into what we call Gjimnaz, the equivalent of High School covering grades 10 to 12, things were even worse academically. I was barely passing anything. There was one moment where a teacher told the weakest students to just pick one topic from two pages of the book and say anything about it to pass. When it got to me I was completely blocked. She could see I was trying to read from the book and told me to close it. I had nothing. I saw the disappointment on her face and I remember thinking I would rather fail cleanly than feel that feeling.</p>
              <p>But tenth grade is also when everything started to change. On January 8, 2021, I prayed for the first time. It was the Maghrib prayer. I had been going back and forth for days, telling myself I would do it tomorrow. That night I just did it. And from that day it became the foundation of everything. If I could choose only one thing to keep from my entire day, it would be that prayer. I structure everything around it, before and after. It gives me peace, focus, and discipline. Above everything else it gives me hope, the kind of hope nothing else in this world comes close to. I believe this life is short, closer to a game than anything permanent, and that there is a next life where every moment of this one will matter. That belief is why I do not want to waste my time and why I do not want to watch other people waste theirs. That is the real reason I do what I do. Not productivity content. Not motivation. I genuinely believe every hour has weight.</p>
              <p>I went to university for Computer Science only because my parents and friends said that is where the money was. I did not even know what the degree actually involved. In the first year I was so lost that my cousin helped me with the admin side of things, the registration, the paperwork, all of that. But inside the actual degree I was drowning on my own. The second year I was completely behind and going in circles. Around this same period I was also trying everything I could think of to change my life. At one point I was enrolled in six courses at the same time, math, religion, cooking, programming, fitness, and communication, with the logic that if one failed I still had the others. On top of that I had a long morning routine, journaling, working out, walking in nature. It was a complete mess. I was trying to do everything at once and getting nothing done properly.</p>
              <p>I once studied for a Java exam and failed it four times. By the third and fourth attempt I was embarrassed just to show up, because that exam was supposed to be one of the easier ones. I gave everything I had and still could not get through it. My sister, who came after me into the same degree and the same subjects, studied for three to four days and passed that exact exam on her first try with a grade of 8. Same material. That comparison said everything about what was happening inside my brain.</p>
              <p>By my third year I could see clearly that I was just falling further and further behind and nothing was moving. I decided I needed to stop and figure things out my own way. I spent months going back and forth on the decision, questioning myself, thinking about it from every angle. Then one day it was just done. The feeling the moment I decided was not fear. It was relief. Like finally being free from an obligation that was never mine to begin with. My parents were not happy. Even after I told them, they still came back from time to time telling me I should go back, that I still had time. I understood why. But for me it was over.</p>
              <p>After I officially made that decision, something shifted. I had spent three or four years reading books, watching videos, trying routines, taking courses, going through everything under the sun. I took all of the things that had actually worked and I put them together into a system. And then I just started. I did an AI course and finished it. I did a Python tutorial and finished it. I built an app and finished it. I made my <Link href="/ultimate-guide" style={{ textDecoration: 'underline', color: 'var(--brand)' }}>Ultimate Guide</Link>, which is my way of turning everything I know about building a system for your life into a format anyone can follow, and I finished that too. I said I would do these things and I did them. This week I finished <Link href="/find-your-direction" style={{ textDecoration: 'underline', color: 'var(--brand)' }}>Finding Your Direction</Link>, a free guide for people who do not yet know what they should be working on. I write on X every week. Every area of my life, working out, reading, doing the most important work, I am more consistent now than I have ever been.</p>
              <p>It was only after all of this, after I started finishing things, that I came across content about ADHD and everything clicked. Looking back at my whole life, every pattern was there. The memory blocks, the freezing under pressure, the confidence collapsing the moment someone said something negative, the complete inability to finish things I had no connection to. I took tests online and scored very high. It all made sense. I was not lazy. My brain&apos;s brakes simply did not work the way they were supposed to. Knowing that was a relief and a hard thing to sit with at the same time, because there is no cure. There are only better ways to work with it.</p>
              <p>Right now I am building a Life OS in Notion. I am giving it everything I have, one deep work session at a time, nothing else competing for that energy. My days are built around my prayers and around this one thing. That is it. Not because I am rigid, but because I have finally learned what it feels like to put your whole energy into something that matters and actually see it move. The proudest moments of my life have come from finishing things, from sitting down, doing the work, and getting it done. The Ultimate Guide was one of those moments. This will be another.</p>
              <p>Everything I went through, the years of switching characters, the failing exams, the loneliness, the feeling of being the one who tries harder than everyone and still fails, I want to put all of that into something that genuinely helps people find their direction and build the discipline to follow it. Because I know what it feels like to have no one tell you that your brain is not broken. It just needs a different system.</p>
              <p>That is what I am here to build.</p>
            </div>
          </div>
        </section>
      </main>

      <footer className="course-footer">
        <p>&copy; 2026 Maurik. All rights reserved.</p>
        <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center', marginTop: '1rem' }}>
          <Link href="/privacy" style={{ color: 'var(--ink-soft)' }}>Privacy Policy</Link>
          <Link href="/terms" style={{ color: 'var(--ink-soft)' }}>Terms of Use</Link>
        </div>
      </footer>
    </div>
  );
}
